<h1 align='center'> COMP2420/COMP6420 - Introduction to Data Management, Analysis and Security</h1>

<h2 align='center'> Homework Assessment 02</h2>

*****

Another week, another set of questions! Woohoo! The following set of **4 questions** test your understanding of the lecture and lab material taught during the lectures and the lab exercises in **Weeks 3 & 4**. In the **next lab (Lab 04)**, you'll be asked to complete any one of these exercises by your tutor in **Exam Mode**. Upon completion, you'll be marked by your tutor, based on the correctness and completeness of your solution.

In [79]:
# RUN THIS CELL TO IMPORT THE REQUIRED MODULES
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
plt.style.use('seaborn')

### Exercise 1 - Big Money Cars

Extending upon our love for cars (especially the pricey ones!), we decided to have a look at the top 5 car manufacturers from the cars dataset. From the below dataset, help us return a dataset comprising of the **top 5 car manufacturers (in descending order)** along with their **average car prices**. But wait, there's a catch! You only have to do these computations on a subset of the dataset that only contains cars with the body-style `sedan` or `convertible`. Your result should look something like this - 

|    _     | company       | price     |
| -------- |:-------------:| ---------:|
|    6     | car_firm 1    |  1000.000 |
|    8     | car_firm 2    |   980.000 |
|   11     | car_firm 3    |   774.333 |
|    3     | car_firm 4    |   645.000 |
|    1     | car_firm 5    |   510.666 |

In [124]:
# TODO: COMPLETE THE BELOW FUNCTION
import numpy as np
def top_5_pricey(df_cars):
    df1 = df_cars.loc[(df_cars['body-style']=='sedan')| (df_cars['body-style']=='convertible')]
    company1 = df1.groupby(['company'],as_index = False).agg(np.mean) #car of same company's mean
    #print(df1)
    #print(company1)
    df2 = company1.sort_values(by=['price'],ascending=False).head(5)
    df2 = df2[['company','price']]
    return df2

In [125]:
# RUN THIS BLOCK TO TEST YOUR CODE
df_cars = pd.read_csv('automobile.csv')
top_5_pricey(df_cars)

          company         price
11        porsche  37028.000000
6          jaguar  34600.000000
8   mercedes-benz  33256.000000
2             bmw  27213.333333
7           mazda  18344.000000

### Exercise 2 - Gotta Catch 'Em All

Now that we've got you motivated to attempt this question with the title itself, let's get on with it! You've been given a dataset with all the defining characteristics of pokémons (a.k.a **Pokédex**). You need to find the pokémon (and its HP) that has the highest HP (Hit Points) for each Type (`Type 1` and `Type 2` both). Because let's face it, that is an important data science question if you need to catch 'em all! :)

In [177]:
# TODO: COMPLETE THE BELOW FUNCTION
def poke_max_hp(df_pokemon):
    #type1Highest = df_pokemon.sort_values(by=['Type 1','Type 2'])
    #df1 = type1Highest[['Type 1','Type 2','Name','HP']]
    
    df1 = df_pokemon.sort_values(by=['HP'],ascending=False)
    df1 = df1.groupby(['Type 1','Type 2'],as_index = False).first() 
    df1 = df1[['Type 1','Type 2','Name','HP']]
    return df1

In [178]:
# RUN THIS BLOCK TO TEST YOUR CODE
df_pokemon = pd.read_csv('pokemon.csv')
poke_max_hp(df_pokemon)

       Type 1    Type 2                     Name   HP
0         Bug  Electric               Galvantula   70
1         Bug  Fighting  HeracrossMega Heracross   80
2         Bug      Fire                Volcarona   85
3         Bug    Flying                  Yanmega   86
4         Bug     Ghost                 Shedinja    1
5         Bug     Grass                 Leavanny   75
6         Bug    Ground      WormadamSandy Cloak   60
7         Bug    Poison                 Venomoth   70
8         Bug      Rock                  Crustle   70
9         Bug     Steel               Forretress   75
10        Bug     Water                  Surskit   40
11       Dark    Dragon                Hydreigon   92
12       Dark  Fighting                  Scrafty   65
13       Dark      Fire                 Houndoom   75
14       Dark    Flying                  Yveltal  126
15       Dark     Ghost                  Sableye   50
16       Dark       Ice                  Weavile   70
17       Dark   Psychic                  Malamar   86
18       Dark     Steel                  Bisharp   65
19     Dragon  Electric                   Zekrom  100
20     Dragon     Fairy      AltariaMega Altaria   75
21     Dragon      Fire                 Reshiram  100
22     Dragon    Flying    RayquazaMega Rayquaza  105
23     Dragon    Ground    GarchompMega Garchomp  108
24     Dragon       Ice                   Kyurem  125
25     Dragon   Psychic                   Latios   80
26   Electric    Dragon    AmpharosMega Ampharos   90
27   Electric     Fairy                  Dedenne   67
28   Electric      Fire          RotomHeat Rotom   50
29   Electric    Flying                   Zapdos   90
..        ...       ...                      ...  ...
106      Rock  Fighting                Terrakion   91
107      Rock    Flying               Aerodactyl   80
108      Rock     Grass                  Cradily   86
109      Rock    Ground                    Golem   80
110      Rock       Ice                  Aurorus  123
111      Rock   Psychic                 Lunatone   70
112      Rock     Steel                Probopass   60
113      Rock     Water               Barbaracle   72
114     Steel    Dragon                   Dialga  100
115     Steel     Fairy                   Klefki   57
116     Steel  Fighting                 Cobalion   91
117     Steel    Flying                 Skarmory   65
118     Steel     Ghost    AegislashShield Forme   60
119     Steel    Ground                  Steelix   75
120     Steel   Psychic                  Jirachi  100
121     Steel      Rock                   Aggron   70
122     Water      Dark    GyaradosMega Gyarados   95
123     Water    Dragon                   Palkia   90
124     Water  Electric                  Lanturn  125
125     Water     Fairy                Azumarill  100
126     Water  Fighting     KeldeoResolute Forme   91
127     Water    Flying                 Gyarados   95
128     Water     Ghost                Jellicent  100
129     Water     Grass                 Ludicolo   80
130     Water    Ground                Gastrodon  111
131     Water       Ice                   Lapras  130
132     Water    Poison               Tentacruel   80
133     Water   Psychic                 Slowking   95
134     Water      Rock                Relicanth  100
135     Water     Steel                 Empoleon   84

[136 rows x 4 columns]

### Exercise 3 - Pump Up The V6

In our quest to find the perfect car to buy, we forgot to analysis the popularity of **no. of cylinders in the car engine** among the various **car manufacturers**. Make a plot that shows us how many companies make a particular `num-of-cylinders` engine. You're free to choose any appropriate plot for this exercise. Don't forget to label and title your plot!

In [193]:
# TODO: COMPLETE THE BELOW FUNCTION
def plot_cyl_companies(df_cars):
    df1 = df_cars.groupby(['num-of-cylinders'].as_index = False).count()
    df2 = df1.groupby(['num-of-cylinders'],as_index = False).count()
    
    
    
    
    return df1

SyntaxError: keyword can't be an expression (<ipython-input-193-cb8a65a9cc6b>, line 3)

In [194]:
# RUN THIS BLOCK TO TEST YOUR CODE
df_cars = pd.read_csv('automobile.csv')
plot_cyl_companies(df_cars)

False

### Exercise 4 - Speed v/s Power

Two of your tutors (whose names shall not be revealed) are fighting over which is a more important characteristic to have while choosing a pokémon for battle. You have to resolve this conflict by drawing a plot to compare the distribution of values for the columns `Speed` and `HP` and also, return a tuple containing the overall mean of both columns.

In [8]:
# TODO: COMPLETE THE BELOW FUNCTION
def poke_conflict_resolution(df_poke):
    
    
    
    return False

In [9]:
# RUN THIS BLOCK TO TEST YOUR CODE
df_pokemon = pd.read_csv('pokemon.csv')
poke_conflict_resolution(df_pokemon)

False